export const OPD=
[{
    name:"abc",
    patientid:"123",
    guardianname:"xyz",
    gender:"male",
    phone:9876543210,
    consultant:"dr.thapa",
    lastvisit:2
    totalvisit:4
},
{
    name:"abc",
    patientid:"123",
    guardianname:"xyz",
    gender:"male",
    phone:9876543210,
    consultant:"dr.thapa",
    lastvisit:2
    totalvisit:4
},
{
    name:"abc",
    patientid:"123",
    guardianname:"xyz",
    gender:"male",
    phone:9876543210,
    consultant:"dr.thapa",
    lastvisit:2
    totalvisit:4
},
{
    name:"abc",
    patientid:"123",
    guardianname:"xyz",
    gender:"male",
    phone:9876543210,
    consultant:"dr.thapa",
    lastvisit:2
    totalvisit:4
}]